title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: "thomasweng.com"
baseurl: "rpad-deadlines"

#twitter_username: abhshkdz
# twitter_hashtag: machinelearning
github_username: thomasweng15
github_repo: rpad-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
